# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  java: 11

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: mvn verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ env.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java }}

      - name: Cache Maven packages
        # FIXME(@JonasCir) #3733 remove '**/*.pom' once serverlib pom is renamed
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-java-${{ env.java }}-m2-${{ hashFiles('**/pom.xml', '**/*.pom') }}
          restore-keys: ${{ runner.os }}-java-${{ env.java }}-m2

      - name: Run mvn verify
        # FIXME(@JonasCir) see https://github.com/hzi-braunschweig/SORMAS-Project/issues/3730#issuecomment-745165678
        working-directory: ./sormas-base
        run: mvn verify -B -ntp

      - name: Commit external visits API spec to development
        if: github.event_name == 'push' && github.ref == 'refs/heads/development' && ${{ hashFiles(sormas-rest/target/external_visits_API.yaml) }} != ${{ hashFiles(openapi/external_visits_API.yaml) }}
        run: |
            token=${{ secrets.SORMAS_VITAGROUP_TOKEN }}
            bot_name=sormas-vitagroup

            REPO_REF="https://${bot_name}:${token}@github.com/${GITHUB_REPOSITORY}.git"
            git config user.name "${bot_name}"
            git config user.email "support.sormas@helpdesk.symeda.de"
            git remote add upstream "${REPO_REF}"

            rm -rf openapi
            mkdir openapi/
            cp sormas-rest/target/external_visits_API.* openapi

            git add openapi
            git commit -m "[GitHub Actions] Update external visits API spec files"
            git push
